function R=Rotation(alpha, beta, gamma)
%X-Y-Z Euler Angle
R=[1 0 0; 0 cos(alpha) -sin(alpha); 0 sin(alpha) cos(alpha)]*...
    [cos(beta) 0 sin(beta); 0 1 0; -sin(beta) 0 cos(beta)]*...
    [cos(gamma) -sin(gamma) 0; sin(gamma) cos(gamma) 0; 0 0 1];
